name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: push-to-ghcr
        uses: macbre/push-to-ghcr@v14
        with:
          github_token: ${{ secrets.DOCKER_TOKEN }}
          image_name: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH & docker compose
        uses: matiasnu/github-action-ssh-docker-compose@v2.0.3
        with:
          # Private SSH key used for logging into remote system.
          ssh_private_key: $ {{ secrets.SERVER_SSH_PRIVATE_KEY }}
          # Remote host name.
          ssh_host: ${{ secrets.SERVER_HOST }}
          # Remote user name.
          ssh_user: $ {{ secrets.SERVER_USERNAME }}
          # Docker compose file to use
          docker_compose_filename: compose.yaml
          # Use docker stack instead of docker compose ("true" or "false").
          # use_stack: # optional, default is false
          # Execute docker compose-down ("true" or "false").
          docker_compose_down: true
          
